### ISSUE TITLE
Define the group `\Z^3`

### ISSUE THREAD

**Issue by 0art0** [siddhartha-gadgil/Polylean#2]
The group `\Z^3` is meant to represent the subgroup `<x, y, z>` in `P`.

One approach to defining this group and the relevant properties is:

- [x] Show that `\Z` is a(n Abelian) group
- [x] Define the product of two (Abelian) groups
- [x] Define a class for free groups consisting of a choice of "basis" and a proof that the group satisfies the universal property for free groups with respect to this choice of basis/generators
- [x] Show that `\Z` is a free group
- [x] Show that the product of two free Abelian groups is free
- [ ] Deduce that a free group is torsion-free
- [x] Show that homomorphisms on a free group are determined by their values on the "basis" elements

Additionally, description of homomorphisms and the associated properties is required:

- [x] Define the notion of a group homomorphism
- [x] Define the image and kernel of a homomorphism, and show that they are groups
- [ ] (Optional) Show that the kernel is a normal subgroup

**Comment by siddhartha-gadgil** [comment]
It is not clear that this much is required. On the other hand, we do want to show that $\Z^3$ is indeed free, not just torsion free.

**Comment by siddhartha-gadgil** [comment]
Further, you do not need to define the notion of "generators of a group" in general for free groups. Indeed that may make things harder. It is better to directly define, for a group F and a set B (list?), that F is a free group with basis B via the universal property.
