### ISSUE TITLE
The cocycle construction

### ISSUE THREAD

**Issue by 0art0** [siddhartha-gadgil/Polylean#5]
This is a general procedure for constructing a group from an Abelian normal subgroup and its quotient, which applies to the group of interest.

Let `K` denote the kernel (assumed to be Abelian), and let `Q` denote the quotient.

## Defining the group action of `Q` on `K`

The cocycle construction first requires fixing an action of `Q` on `K` via automorphisms. One possible way to define this in Lean is as follows:

~- [ ] Define the monoid `End(G)` for any group `G`.~
~- [ ] An action of a group `Q` on `G` via automorphisms is then just a monoid homomorphism from `Q` to `End(G)`. This can be turned into an instance of a group action of `Q` on `K` in the usual sense.~
~- [ ] For convenience, group actions via automorphisms can be made into a separate typeclass.~

- `a (x + y) = ax + ay`
- `(a + b)x = a(bx)` 
- `a 0 = 0`
- `0 x = x`

- [x] Define group actions by automorphisms

## Defining cocycles for group actions via automorphisms

Given an action of `Q` on `K` via automorphisms, a cocycle for it is a function `c : Q -> Q -> K` satisfying:

- `∀ q : Q, c(q, e) = 0 = c(e, q)`
- `∀ q : Q, c(q, q⁻¹) = c(q⁻¹, q)`
- **Cocycle condition:** `∀ q q' q'' : Q, c(q, q') + c(qq', q'') = q • c(q', q'') + c(q, q'q'')` 

The first two properties here may be redundant. These can be conveniently packages into a structure or a typeclass.

- [x] Create typeclass for cocycles for actions

## Defining the group structure

Given an action and a cocycle, one can define a group extending `K` and `Q` as follows:

- The underlying set is just the Cartesian product `K x Q`
-  The multiplication is given by `(k, q), (k', q') |--> (k + q • k' + c(q, q'), qq')` 
- The identity is `(0, e_Q)`
- The inverse of `(k, q)` is `(-q⁻¹ • k, - q⁻¹ • c(q, q⁻¹), q⁻¹)`
- The properties of the group follow directly from these definitions. Associativity crucially uses the cocycle condition.

- [x] Given an action and a cocycle, define the group operation
- [x] Define identity and inverse operation, and prove the required properties
- [x] Prove associativity using the cocycle condition
- [x] Define a group structure on `K x Q` using the above
- [ ] (Optional) Define the injection from the kernel `K` to the Metabelian group

## Specialising to Gardam's example

With the above constructions in place, the group of interest can be defined using the action and cocycle defined on page 5 of [https://arxiv.org/pdf/2102.11818.pdf](Gardam's paper). This will first require proving some basic facts about automorphisms on free groups, after which most of the properties can be verified by considering cases and computation.

**Comment by siddhartha-gadgil** [comment]
* There is no need to define `End(G)`, one can more directly define the properties needed. Also a more direct definition means one does not have to unwrap the definitions with used.
* The properties needed (for an additive group) are:
    1. `a (x + y) = ax + ay`
    2. `(ab)x` = `a(bx)` - when the group `Q` is additive this is `(ab)x = (a + b)x`
    3. `a 0 = 0`
    4. `e x = x`
Indeed the last two are probably redundant (3 is for sure), but easy to check anyway.

**Comment by siddhartha-gadgil** [comment]
Specifically, here is my view of steps:

- [ ] Define group actions for additive groups on additive groups : this is a typeclass on functions `A -> B -> B` with `A` and `B` additive groups.
- [ ] Define the cocycle condition : typeclass for functions `A -> A -> B` with `A` and `B` additive groups.
- [ ] Define the Metabelian group _operation_ given a group action and a typeclass.
- [ ] Show that the group operation is associative.
- [ ] Complete the result that this is a group.
